---
id: Mime
name: Mime
full: MIME library
description: >-
  A library that provides methods for dealing with Multipurpose Internet Mail
  Extensions (MIME) features (RFC 2045/2046/2047).
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Mime
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/listheaders: ^2
      horde/mail: ^3
      horde/stream: ^2
      horde/stream_filter: ^3
      horde/support: ^3
      horde/text_flowed: ^3
      horde/text_filter: ^3
      horde/translation: ^3
      horde/util: ^3
  optional:
    composer:
      horde/nls: ^3
      horde/test: ^3
      horde/text_filter: ^3
      pear/net_dns2: '*'
    ext:
      idn: '*'
      intl: '*'
